import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/globals.css"
import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/Footer";

//import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | Test Nextjs',
    default: "Salud Virtual",
  },
  description: "Generated by create next app",
};
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <Navbar />  
        <main className="flex flex-col items-center min-h-screen container">
          {children}
        </main> 
        <Footer />
      </body>
    </html>
  );
}
